# prometheus-values.yaml
grafana:
  adminPassword: "admin" # 초기 비밀번호 설정
  service:
    type: NodePort # 외부 접속을 위해 NodePort로 변경

prometheus:
  prometheusSpec:
    # ServiceMonitor를 찾을 때 사용할 레이블 규칙
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
